WebNC_Project/Models/Booking.cs
namespace WebNC_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Spatial;
    using System.Linq;

    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            BookingServices = new HashSet<BookingServices>();
        }
        [Display(Name = "Mã hóa đơn")]
        public int ID { get; set; }

        [MaxLength(20,ErrorMessage ="{0} contains at most 20 characters")]
        [Required(ErrorMessage = "{0} is required")]
        [Display(Name = "Khách hàng")]
        public string CustomerID { get; set; }

        [Required(ErrorMessage = "{0} is required")]
        [MaxLength(10,ErrorMessage ="{0} contains at most 10 characters")]
        [Display(Name = "Phòng")]
        public string RoomID { get; set; }

        [Required(ErrorMessage = "{0} is required")]
        [Display(Name = "Ngày Check in")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime CheckinDate { get; set; }

        [Required(ErrorMessage = "{0} is required")]
        [Display(Name = "Ngày Check out")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime CheckoutDate { get; set; }

        [Display(Name = "Trạng thái")]
        public string Status { get; set; }

        [Range(1,int.MaxValue,ErrorMessage = "{0} is not valid")]
        [Display(Name = "Người lớn")]
        [Required(ErrorMessage = "{0} is required")]
        public int Adult { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "{0} is not valid")]
        [Display(Name = "Trẻ em")]
        public int Child { get; set; }

        [MaxLength(20, ErrorMessage = "{0} contains at most 20 characters")]
        [Display(Name = "Mã voucher")]
        [RegularExpression(@"^[A-Z0-9]{6,20}$",ErrorMessage = "Voucher code not valid")]
        public string VoucherCode { get; set; }

        public string FeedBack { get; set; }

        public int? Rate { get; set; }

        public virtual Customer Customer { get; set; }

        public virtual Room Room { get; set; }

        public virtual Voucher Voucher { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingServices> BookingServices { get; set; }

        [NotMapped]
        public string GetStatus
        {
            get
            {
                switch (Status) {
                    case "checkin": return "Check In";
                    case "checkout": return "Check Out";
                    case "confirm": return "Đã xác nhận";
                    case "cancel": return "Cancel";
                    case "payment": return "Đã thanh toán";
                    default: return "Chờ xác nhận";
                }
            }
        }

        [NotMapped] 
        public string GetColor
        {
            get
            {
                switch (Status)
                {
                    case "checkin": return "warning";
                    case "checkout": return "success";
                    case "confirm": return "success";
                    case "cancel": return "danger";
                    case "payment": return "success";
                    default: return "secondary";
                }
            }
        }

        public static double GetPrice(Booking booking, bool IncludeVoucher = true)
        {
            double price = booking.Room.Price * booking.CheckoutDate.Date.Subtract(booking.CheckinDate.Date).Days;
            if (booking.BookingServices.Count() > 0)
            {
                foreach (var sv in booking.BookingServices)
                {
                    price += sv.Service.Price;
                }
            }
            if(booking.VoucherCode != null && IncludeVoucher)
            {
                price = price * ((100 - booking.Voucher.Discount) / 100.0);
            }
            return price;
        }

        public static string ValidCheckin(DateTime checkin, DateTime min)
        {
            if(checkin.Date < min.Date || checkin.Date > min.AddMonths(1).Date)
            {
                return $"Checkin Date must be beetwen {DateTime.Now.AddDays(1).ToString("dd/MM/yyyy")} to {DateTime.Now.AddDays(1).AddMonths(1).ToString("dd/MM/yyyy")}";
            }
            return null;
        }

        [NotMapped]
        public string ValidCheckout
        {
            get
            {
                if (CheckinDate.AddMonths(1).Date < CheckoutDate.Date) return $"Check Out date must be between {CheckinDate.AddDays(1).ToString("dd/MM/yyyy")} to {CheckinDate.AddDays(1).AddMonths(1).ToString("dd/MM/yyyy")}";
                return null;
            }
        }

        public bool CanEdit()
        {
            return Status == null || DateTime.Now.Date < CheckinDate.Date && Status != "payment";
        }

        public bool CanFeedBack()
        {
            return Status == "payment" && CheckoutDate.Date <= DateTime.Now.Date;
        }

        public bool CanPay()
        {
            return Status != "payment" && Status != "cancel" && Status != null;
        }
    }

}

WebNC_Project/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Stripe.Infrastructure;
using System.Web.Mvc;
using System.Threading.Tasks;
using WebNC_Project.Models;
using WebNC_Project.DAO;
using WebNC_Project.App_Start;
using Stripe.Checkout;
using Stripe;
using WebNC_Project.ViewModel;

namespace WebNC_Project.Controllers
{
    [CustomerAuthentication]
    public class BookingController : Controller
    {
        // GET: Booking
        public async Task<ActionResult> Index()
        {
            var result = await BookingDAO.BookingsOfCustomer((string)Session["Customer"]);
            return View(result);
        }

        public async Task<ActionResult> Create(string room)
        {
            ViewBag.ListRoom = await ListRoom();
            DateTime today = DateTime.Now.AddDays(1);
            Booking booking = new Booking()
            {
                CustomerID = (string)Session["Customer"],
                RoomID = room,
                CheckinDate = today.Date,
                CheckoutDate = today.AddDays(1).Date
            };
            return View(booking);
        }

        [HttpPost]
        [Obsolete]
        public async Task<ActionResult> Create(Booking model)
        {
            ViewBag.ListRoom = await ListRoom();
            if (!ModelState.IsValid) return View(model);
            if(!(await CustomerDAO.CanBooking((string)Session["Customer"])))
            {
                ModelState.AddModelError("RoomID", "You already have a order and can not book more");
                return View(model);
            }
            if(model.CheckinDate.Date >= model.CheckoutDate.Date)
            {
                ModelState.AddModelError("CheckinDate", "Check in date must smaller than check out date");
                return View(model);
            }
            if(!(await RoomDAO.CheckRoom(model.RoomID, model.CheckinDate, model.CheckoutDate)))
            {
                ModelState.AddModelError("RoomID", $"Can not book this room from {model.CheckinDate.ToString("dd/MM/yyyy")} to {model.CheckoutDate.ToString("dd/MM/yyyy")}");
                return View(model);
            }
            var room = await RoomDAO.GetByID(model.RoomID);
            if (room.Adult < model.Adult)
            {
                ModelState.AddModelError("Adult", $"Max adult of room {model.RoomID} is {room.Adult}");
                return View(model);
            }
            if (room.Child < model.Child)
            {
                ModelState.AddModelError("Child", $"Max child of room {model.RoomID} is {room.Child}");
                return View(model);
            }
            string validCheckIn = Booking.ValidCheckin(model.CheckinDate, DateTime.Now);
            if (validCheckIn != null)
            {
                ModelState.AddModelError("CheckinDate", validCheckIn);
                return View(model);
            }
            if (model.ValidCheckout != null)
            {
                ModelState.AddModelError("CheckoutDate", model.ValidCheckout);
                return View(model);
            }
            if (model.VoucherCode != null)
            {
                var voucher = await VoucherDAO.GetByID(model.VoucherCode);
                if (voucher == null)
                {
                    ModelState.AddModelError("VoucherCode", $"Voucher {model.VoucherCode} does not existed");
                    return View(model);
                }
                if (!(voucher.FromDate.Date <= model.CheckinDate.Date && model.CheckinDate.Date <= voucher.ToDate.Date) &&
                !(voucher.FromDate.Date <= model.CheckoutDate.Date && model.CheckoutDate.Date <= voucher.ToDate.Date))
                {
                    ModelState.AddModelError("VoucherCode", $"Voucher {voucher.Code} can apply for bill booking between {voucher.FromDate.ToString("dd/MM/yyyyy")} and {voucher.ToDate.ToString("dd/MM/yyyyy")}");
                    return View(model);
                }
                model.Room = await RoomDAO.GetByID(model.RoomID);
                if(Booking.GetPrice(model, false) < voucher.Condition)
                {
                    ModelState.AddModelError("VoucherCode", $"Voucher {voucher.Code} can apply for bill with value equal or bigger than {voucher.Condition} VND");
                    return View(model);
                }
            }
            try
            {
                await BookingDAO.Create(model);
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                ModelState.AddModelError("RoomID", "An exception when create your booking request");
                return View(model);
            }
        }

        public async Task<ActionResult> Edit(int id)
        {
            ViewBag.ID = id;
            ViewBag.ListRoom = await ListRoom();
            var result = await BookingDAO.GetByID(id);
            return PartialView(result);
        }

        [HttpPost]
        [Obsolete]
        public async Task<ActionResult> Edit(Booking model)
        {
            ViewBag.ListRoom = await ListRoom();
            if (!ModelState.IsValid) return PartialView(model);
            if (!(await RoomDAO.CheckRoom(model.RoomID, model.CheckinDate, model.CheckoutDate, model.ID)))
            {
                ModelState.AddModelError("RoomID", $"Can not book this room from {model.CheckinDate.ToString("dd/MM/yyyy")} to {model.CheckoutDate.ToString("dd/MM/yyyy")}");
                return PartialView(model);
            }
            if (model.CheckinDate.Date >= model.CheckoutDate.Date)
            {
                ModelState.AddModelError("CheckinDate", "Check in date must smaller than check out date");
                return PartialView(model);
            }
            var room = await RoomDAO.GetByID(model.RoomID);
            if (room.Adult < model.Adult)
            {
                ModelState.AddModelError("Adult", $"Max adult of room {model.RoomID} is {room.Adult}");
                return PartialView(model);
            }
            if (room.Child < model.Child)
            {
                ModelState.AddModelError("Child", $"Max child of room {model.RoomID} is {room.Child}");
                return PartialView(model);
            }
            string validCheckIn = Booking.ValidCheckin(model.CheckinDate, model.CheckinDate);
            if (validCheckIn != null)
            {
                ModelState.AddModelError("CheckinDate", validCheckIn);
                return PartialView(model);
            }
            if (model.ValidCheckout != null)
            {
                ModelState.AddModelError("CheckoutDate", model.ValidCheckout);
                return PartialView(model);
            }
            if (model.VoucherCode != null)
            {
                var voucher = await VoucherDAO.GetByID(model.VoucherCode);
                if (voucher == null)
                {
                    ModelState.AddModelError("VoucherCode", $"Voucher {model.VoucherCode} does not existed");
                    return PartialView(model);
                }
                if (!(voucher.FromDate.Date <= model.CheckinDate.Date && model.CheckinDate.Date <= voucher.ToDate.Date) &&
                !(voucher.FromDate.Date <= model.CheckoutDate.Date && model.CheckoutDate.Date <= voucher.ToDate.Date))
                {
                    ModelState.AddModelError("VoucherCode", $"Voucher {voucher.Code} can apply for bill booking between {voucher.FromDate.ToString("dd/MM/yyyyy")} and {voucher.ToDate.ToString("dd/MM/yyyyy")}");
                    return PartialView(model);
                }
                var bill = await BookingDAO.GetByID(model.ID);
                model.Room = bill.Room;
                model.BookingServices = bill.BookingServices;
                if (Booking.GetPrice(model, false) < voucher.Condition)
                {
                    ModelState.AddModelError("VoucherCode", $"Voucher {voucher.Code} can apply for bill with value equal or bigger than {voucher.Condition} VND");
                    return PartialView(model);
                }
            }
            try
            {
                await BookingDAO.Edit(model);
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                ModelState.AddModelError("", $"Error when edit information of booking #{model.ID}");
                return PartialView(model);
            }
        }

        public async Task<ActionResult> CallServices(int id)
        {
            ViewBag.ID = id;
            ViewBag.ListSV = await BookingDAO.GetServicesOfBill(id);
            var result = await ServiceDAO.GetAll();
            return PartialView(result);
        }

        [HttpPost]
        public async Task<ActionResult> AddSV(BookingServices model)
        {
            try
            {
                await BookingDAO.AddSV(model);
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public async Task<ActionResult> RemoveSV(BookingServices model)
        {
            try
            {
                await BookingDAO.RemoveSV(model);
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public async Task<ActionResult> Cancel(int id)
        {
            var enti = await BookingDAO.GetByID(id);
            if(enti.Status != null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            try
            {
                await BookingDAO.CheckBooking(id, "cancel");
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            catch
            {

WebNC_Project/Views/Booking/CallServices.cshtml
@model IEnumerable<WebNC_Project.Models.Service>

@{
    ViewBag.Title = "CallServices";
    IEnumerable<string> listSV = ViewBag.ListSV;
    int id = ViewBag.ID;
}
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Dịch vụ cho hóa đơn #@id</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <div class="row">
        @foreach(var item in Model)
        {
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Dịch vụ: @item.Name</h5>
                        <p class="card-text">Giá sử dụng: @item.Price $</p>
                        @if (listSV.Contains(item.ID))
                        {
                            <button class="btn btn-danger" onclick="RemoveSV(@id,'@(item.ID.Trim())')">Remove</button>
                        }
                        else
                        { 
                            <button class="btn btn-success" onclick="AddSV(@id, '@(item.ID.Trim())')">Add</button>
                        }
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>

WebNC_Project/Views/Booking/Create.cshtml
@model WebNC_Project.Models.Booking

@{
    ViewBag.Title = "Create";
    SelectList listRooms = ViewBag.ListRoom;
}

<!-- Breadcrumb Section Begin -->
<div class="breadcrumb-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-text">
                    <h2>Booking</h2>
                    <div class="bt-option">
                        <a href="javascript(void:0)">Booking</a>
                        <span>Create new</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb Section End -->
<section class="contact-section spad">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="about-page-text">
                    <div class="row">
                        <div class="col">
                            <div class="ap-title">
                                <h2>Thank for using our services.</h2>
                                <p>
                                    Built in 1910 during the Belle Epoque period, this hotel is located in the center of
                                    Paris, with easy access to the city’s tourist attractions. It offers tastefully
                                    decorated rooms.
                                </p>
                                <ul class="ap-services">
                                    <li><i class="icon_check"></i> Complimentary Daily Breakfast</li>
                                    <li><i class="icon_check"></i> Modern equipment</li>
                                    <li><i class="icon_check"></i> Free Wifi.</li>
                                    <li><i class="icon_check"></i> Discount for bill</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8 booking-form">
                @using (Html.BeginForm("Create", "Booking", FormMethod.Post, new { @class = "contact-form" }))
                {
                    @Html.ValidationSummary(true)
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(m => m.CustomerID)
                    <div class="row">
                        <div class="col-md-2">
                            @Html.LabelFor(m => m.RoomID)
                        </div>
                        <div class="col-md-10 select-option">
                            @Html.DropDownListFor(m => m.RoomID, listRooms, new { @placeholder = "Select Room", @class = "select-list" })
                            @Html.ValidationMessageFor(m => m.RoomID, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-2">
                            @Html.LabelFor(m => m.CheckinDate)
                        </div>
                        <div class="col-md-10">
                            @Html.EditorFor(m => m.CheckinDate, new { htmlAttributes = new { @placeholder = "Enter check in date", @class = "date-input" } })
                            @Html.ValidationMessageFor(m => m.CheckinDate, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-2">
                            @Html.LabelFor(m => m.CheckoutDate)
                        </div>
                        <div class="col-md-10">
                            @Html.EditorFor(m => m.CheckoutDate, new { htmlAttributes = new { @placeholder = "Enter check out date", @class = "date-input" } })
                            @Html.ValidationMessageFor(m => m.CheckoutDate, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-2">
                            @Html.LabelFor(m => m.Adult)
                        </div>
                        <div class="col-md-10">
                            @Html.EditorFor(m => m.Adult, new { htmlAttributes = new { @placeholder = "Enter number of adult" } })
                            @Html.ValidationMessageFor(m => m.Adult, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-2">
                            @Html.LabelFor(m => m.Child)
                        </div>
                        <div class="col-md-10">
                            @Html.EditorFor(m => m.Child, new { htmlAttributes = new { @placeholder = "Enter number of child" } })
                            @Html.ValidationMessageFor(m => m.Child, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-2">
                            @Html.LabelFor(m => m.VoucherCode)
                        </div>
                        <div class="col-md-10">
                            @Html.EditorFor(m => m.VoucherCode, new { htmlAttributes = new { @placeholder = "Enter voucher code if you have" } })
                            @Html.ValidationMessageFor(m => m.VoucherCode, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-12 mt-3">
                            <button type="submit">Book Now</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

WebNC_Project/Views/Booking/Edit.cshtml
@model WebNC_Project.Models.Booking

@{
    SelectList listRooms = ViewBag.ListRoom;
}
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Cập nhật hóa đơn #@Model.ID</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form id="edit_form">
        @Html.ValidationMessage("", new { @class = "text-danger" })
        @Html.HiddenFor(m => m.ID)
        @Html.HiddenFor(m => m.CustomerID)
        <div class="form-group">
            @Html.LabelFor(m => m.RoomID, new { @class = "col-form-label" })
            @Html.DropDownListFor(m => m.RoomID, listRooms, new { @class = "select-list form-control" })
            @Html.ValidationMessageFor(m => m.RoomID, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.CheckinDate, new { @class = "col-form-label" })
            @Html.EditorFor(m => m.CheckinDate, new { htmlAttributes = new { @class = "date-picker form-control" } })
            @Html.ValidationMessageFor(m => m.CheckinDate, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.CheckoutDate, new { @class = "col-form-label" })
            @Html.EditorFor(m => m.CheckoutDate, new { htmlAttributes = new { @class = "date-picker form-control" } })
            @Html.ValidationMessageFor(m => m.CheckoutDate, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Adult, new { @class = "col-form-label" })
            @Html.EditorFor(m => m.Adult, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.Adult, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Child, new { @class = "col-form-label" })
            @Html.EditorFor(m => m.Child, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.Child, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.VoucherCode, new { @class = "col-form-label" })
            @Html.EditorFor(m => m.VoucherCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.VoucherCode, "", new { @class = "text-danger" })
        </div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="button" class="btn btn-primary" onclick="SubmitEdit()">Submit</button>
</div>
<script>
    $(".date-picker").datepicker({
        minDate: 0,
        dateFormat: 'dd/mm/yy'
    });
</script>

WebNC_Project/Views/Booking/ErrorPayment.cshtml
@{
    ViewBag.Title = "ErrorPayment";
}

<!-- Breadcrumb Section Begin -->
<div class="breadcrumb-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-text">
                    <h2>Booking</h2>
                    <div class="bt-option">
                        <a href="javascript(void:0)">Booking</a>
                        <span>Error</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb Section End -->
<section class="contact-section spad">
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="about-page-text">
                    <div class="row">
                        <div class="col">
                            <div class="ap-title">
                                <h2>Sorry for this problems</h2>
                                <p>
                                    Some error when you try to payment a booking!!!
                                </p>
                                <p>
                                    Please try again.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

WebNC_Project/Views/Booking/Payment.cshtml
@{
    ViewBag.Title = "Payment";
    WebNC_Project.Models.Booking bill = ViewBag.Bill;
}
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Thanh toán hóa đơn #@bill.ID</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    @using (Html.BeginForm("Payment", "Booking", FormMethod.Post, new { @id = "payment-form" }))
    {
        @Html.Hidden("BillID",bill.ID)
        <div class="form-group">
            <label for="card-name">Card Name</label>
            <input type="text" class="form-control" id="card-name" name="card-name" placeholder="Card Name" required>
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Email" value="@bill.Customer.Email" required>
        </div>
        <div class="form-group">
            <label for="phone">Phone</label>
            <input type="tel" class="form-control" id="phone" name="phone" placeholder="Phone" value="@bill.Customer.Phone" required>
        </div>
        <div class="form-group">
            <label for="card-number">
                Credit or debit card
            </label>
            <div id="card-number" class="form-control">
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-md-6">
                    <label for="card-cvc">
                        CVC
                    </label>
                    <div id="card-cvc" class="form-control">
                    </div>
                </div>
                <div class="col-md-6">
                    <label for="card-exp">
                        EXP
                    </label>
                    <div id="card-exp" class="form-control">
                    </div>
                </div>
            </div>
        </div>
        <!-- Used to display Element errors. -->
        <div id="card-errors" role="alert" class="text-danger"></div>

        <div class="form-group">
            <button class="btn btn-primary btn-block">Submit Payment</button>
        </div>
    }
</div>
<script type="text/javascript">
    var stripe = Stripe("pk_test_51J08eWItPwG3qPODYiIl6BfdFV2GdubPj6cYjvUJqSyFamWLkdAnc6Ynoe4siIdDiTLOMAgJh253Tk1Jyjg735gP00F2JYMAgJ");
    var elements = stripe.elements();
    var style = {
        base: {
            color: "#32325d",
            fontFamily: 'Arial, sans-serif',
            fontSmoothing: "antialiased",
            fontSize: "16px",
            "::placeholder": {
                color: "#32325d"
            }
        },
        invalid: {
            fontFamily: 'Arial, sans-serif',
            color: "#fa755a",
            iconColor: "#fa755a"
        }
    };
    var card = elements.create("cardNumber");
    var cvc = elements.create("cardCvc");
    var exp = elements.create("cardExpiry");
    // Stripe injects an iframe into the DOM
    card.mount("#card-number");
    cvc.mount("#card-cvc");
    exp.mount("#card-exp");
    card.addEventListener('change', function (event) {
        var displayError = document.getElementById('card-errors');
        if (event.error) {
            displayError.textContent = event.error.message;
        } else {
            displayError.textContent = '';
        }
    });
    // Create a token or display an error when the form is submitted.
    var form = document.getElementById('payment-form');
    form.addEventListener('submit', function (event) {
        event.preventDefault();

        stripe.createToken(card).then(function (result) {
            if (result.error) {
                // Inform the customer that there was an error.
                var errorElement = document.getElementById('card-errors');
                errorElement.textContent = result.error.message;
            } else {
                // Send the token to your server.
                stripeTokenHandler(result.token);
            }
        });
    });
    function stripeTokenHandler(token) {
        // Insert the token ID into the form so it gets submitted to the server
        var form = document.getElementById('payment-form');
        var hiddenInput = document.createElement('input');
        hiddenInput.setAttribute('type', 'hidden');
        hiddenInput.setAttribute('name', 'stripeToken');
        hiddenInput.setAttribute('value', token.id);
        form.appendChild(hiddenInput);

        // Submit the form
        form.submit();
    }
</script>