WebNC_Project/Models/Voucher.cs
namespace WebNC_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Voucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voucher()
        {
            Bookings = new HashSet<Booking>();
            FromDate = DateTime.Now;
            ToDate = DateTime.Now.AddDays(1);
        }

        [Key]
        [MaxLength(20,ErrorMessage = "{0} constain at most 20 characters")]
        [MinLength(6, ErrorMessage = "{0} constain at least 6 characters")]
        [Required(ErrorMessage = "{0} is required")]
        [Display(Name = "Mã voucher")]
        public string Code { get; set; }

        [Required(ErrorMessage = "{0} is required")]
        [Range(1,100,ErrorMessage = "{0} from 1 to 100")]
        public int Discount { get; set; }

        [Column(TypeName = "datetime2")]
        [Required(ErrorMessage = "{0} is required")]
        [Display(Name = "Từ ngày")]
        public DateTime FromDate { get; set; }

        [Column(TypeName = "datetime2")]
        [Required(ErrorMessage = "{0} is required")]
        [Display(Name = "Đến ngày")]
        public DateTime ToDate { get; set; }

        [Required(ErrorMessage = "{0} is required")]
        [Display(Name = "Giá trị áp dụng tối thiểu")]
        public int Condition { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}

WebNC_Project/Areas/Server/Controllers/VouchersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebNC_Project.Models;
using WebNC_Project.DAO;
using System.Threading.Tasks;

namespace WebNC_Project.Areas.Server.Controllers
{
    [ServerAuthentication]
    public class VouchersController : Controller
    {
        // GET: Server/Vouchers
        [ServerAuthorize("STAFF")]
        public async Task<ActionResult> Index(string search)
        {
            ViewBag.Search = search;
            return View(await VoucherDAO.GetAll());
        }

        // GET: Server/Vouchers/Details/5
        [ServerAuthorize("STAFF")]
        public async Task<ActionResult> Details(string id)
        {
            var result = await VoucherDAO.GetByID(id);
            return View(result);
        }

        // GET: Server/Vouchers/Create
        [ServerAuthorize]
        public ActionResult Create()
        {
            return View(new Voucher());
        }

        // POST: Server/Vouchers/Create
        [HttpPost]
        [ServerAuthorize]
        public async Task<ActionResult> Create(Voucher voucher)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if(CheckDate(voucher.FromDate, voucher.ToDate))
                    {
                        ModelState.AddModelError("ToDate", "The date end of voucher was not valid");
                        return View(voucher);
                    }
                    if (voucher.FromDate.Date <= DateTime.Today.Date)
                    {
                        ModelState.AddModelError("FromDate", "The date begin of voucher cannot smaller than to day");
                        return View(voucher);
                    }
                    var entity = await VoucherDAO.GetByID(voucher.Code);
                    if (entity != null)
                    {
                        ModelState.AddModelError("Code", "Code was exist, try again with new Code");
                        return View(voucher);
                    }
                    await VoucherDAO.Create(voucher);
                    return RedirectToAction("Index");
                }
                return View(voucher);
            }
            catch
            {
                ModelState.AddModelError("", "Server can not create supply");
                return View(voucher);
            }
        }

        // GET: Server/Vouchers/Edit/5
        [ServerAuthorize]
        public async Task<ActionResult> Edit(string id)
        {
            var result = await VoucherDAO.GetByID(id);
            return View(result);
        }

        // POST: Server/Vouchers/Edit/5
        [HttpPost]
        [ServerAuthorize]
        public async Task<ActionResult> Edit(Voucher voucher)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (CheckDate(voucher.FromDate, voucher.ToDate))
                    {
                        ModelState.AddModelError("ToDate", "The date end of voucher was not valid");
                        return View(voucher);
                    }
                    var enti = await VoucherDAO.GetByID(voucher.Code);
                    DateTime min = DateTime.Now;
                    if (enti.FromDate.Date < DateTime.Now.Date) min = enti.FromDate.Date;
                    if(voucher.FromDate.Date < min.Date)
                    {
                        ModelState.AddModelError("FromDate", $"The date begin of voucher cannot smaller than {min.ToString("dd/MM/yyyy")}");
                        return View(voucher);
                    }
                    await VoucherDAO.Edit(voucher);
                    return RedirectToAction("Details", new { id = voucher.Code.Trim() });
                }
                return View(voucher);

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(voucher);
            }
        }

        // POST: Server/Vouchers/Delete/5
        [HttpPost]
        [ServerAuthorize]
        public async Task<ActionResult> Remove(string id)
        {
            var result = VoucherDAO.GetByID(id);
            if (result == null) return new HttpStatusCodeResult(System.Net.HttpStatusCode.NotFound);
            try
            {
                await VoucherDAO.Remove(id);
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.OK);
            }
            catch
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
        }

        private bool CheckDate(DateTime from, DateTime to)
        {
            return from.CompareTo(to) == 1 ? true : false;
        }
    }
}

WebNC_Project/Controllers/VoucherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using WebNC_Project.DAO;
using WebNC_Project.Models;

namespace WebNC_Project.Controllers
{
    public class VoucherController : Controller
    {
        // GET: Voucher
        public async Task<ActionResult> Index(int? page, string search)
        {
            int pageSize = 6;
            int pageNum = (page ?? 1);
            IEnumerable<Voucher> result;
            if (search == null)
            {
                result = await VoucherDAO.GetAvailable();
            }
            else
            {
                result = await VoucherDAO.Search(search);
            }
            return View(result.ToPagedList(pageNum,pageSize));
        }
    }
}

WebNC_Project/Areas/Server/Views/Vouchers/Create.cshtml
@model WebNC_Project.Models.Voucher

@{
    ViewBag.Title = "Thêm mới Voucher";
}
@section styles {
    <link href="~/Areas/Server/resources/plugins/bootstrap-datepicker/css/bootstrap-datepicker.css" rel="stylesheet" />
}
<div class="card">
    <div class="header">
        <h2>
            @ViewBag.Title.ToUpper()
        </h2>
    </div>
    <div class="body">
        @using (Html.BeginForm(null, null, FormMethod.Post, new { @id="submitFrm" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @Html.LabelFor(s => s.Code)
            <div class="form-group">
                <div class="form-line">
                    @Html.EditorFor(s => s.Code, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                @Html.ValidationMessageFor(s => s.Code, "", new { @class = "text-danger" })
            </div>
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    @Html.LabelFor(s => s.FromDate)
                    <div class="form-group">
                        <div class="form-line bs_datepicker_from">
                            @Html.EditorFor(s => s.FromDate, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        @Html.ValidationMessageFor(s => s.FromDate, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    @Html.LabelFor(s => s.ToDate)
                    <div class="form-group">
                        <div class="form-line bs_datepicker_to">
                            @Html.EditorFor(s => s.ToDate, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        @Html.ValidationMessageFor(s => s.ToDate, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    @Html.LabelFor(s => s.Condition)
                    <div class="form-group">
                        <div class="form-line">
                            @Html.EditorFor(s => s.Condition, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        @Html.ValidationMessageFor(s => s.Condition, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    @Html.LabelFor(s => s.Discount)
                    <div class="form-group">
                        <div class="form-line">
                            @Html.EditorFor(s => s.Discount, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        @Html.ValidationMessageFor(s => s.Discount, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <button class="btn btn-primary waves-effect" type="submit" onclick="IsSubmit(this, event)">SUBMIT</button>
        }
    </div>
</div>
@section scripts {
    <script src="~/Areas/Server/resources/plugins/momentjs/moment.js"></script>
    <script src="~/Areas/Server/resources/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script>
        $(function () {
            $('.bs_datepicker_from input').datepicker({
                autoclose: true,
                container: '.bs_datepicker_from',
                format: 'dd/mm/yyyy' 
            });
            $('.bs_datepicker_to input').datepicker({
                autoclose: true,
                container: '.bs_datepicker_to',
                format: 'dd/mm/yyyy' 
            });
        })
    </script>
}

WebNC_Project/Areas/Server/Views/Vouchers/Details.cshtml
@model WebNC_Project.Models.Voucher

@{
    ViewBag.Title = "Thông tin Voucher";
    string role = Session["Role"] as string;
}
@section styles {
    <link href="~/Areas/Server/resources/plugins/sweetalert/sweetalert.css" rel="stylesheet" />
}
<div class="card">
    <div class="header">
        <h2>
            @ViewBag.Title.ToUpper()
        </h2>
    </div>
    <div class="body">
        <div class="panel panel-default panel-post">
            <div class="panel-heading">
                <h4>@Html.DisplayNameFor(s => s.Code) : @Model.Code</h4>
            </div>
            <div class="panel-body">
                <div class="list-group font-16">
                    <div class="list-group-item">
                        <div class="row">
                            <div class="col-md-3">
                                @Html.DisplayNameFor(s => s.FromDate)
                            </div>
                            <div class="col-md-9">
                                @Model.FromDate.ToString("dd/MM/yyyy")
                            </div>
                        </div>
                    </div>
                    <div class="list-group-item">
                        <div class="row">
                            <div class="col-md-3">
                                @Html.DisplayNameFor(s => s.ToDate)
                            </div>
                            <div class="col-md-9">
                                @Model.ToDate.ToString("dd/MM/yyyy")
                            </div>
                        </div>
                    </div>
                    <div class="list-group-item">
                        <div class="row">
                            <div class="col-md-3">
                                @Html.DisplayNameFor(s => s.Discount)
                            </div>
                            <div class="col-md-9">
                                @Model.Discount %
                            </div>
                        </div>
                    </div>
                    <div class="list-group-item">
                        <div class="row">
                            <div class="col-md-3">
                                @Html.DisplayNameFor(s => s.Condition)
                            </div>
                            <div class="col-md-9">
                                &GreaterEqual; @Model.Condition
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @if (role == "MANAGER")
            {
                <div class="panel-footer">
                    <div class="btn-group btn-group-justified" role="group" aria-label="Justified button group">
                        <a href="@Url.Action("Edit","Vouchers", new { id = Model.Code.Trim() })" class="btn btn-primary waves-effect">
                            <i class="material-icons">edit</i>
                            <span>EDIT</span>
                        </a>
                        <a href="javascript:void(0);" role="button" class="btn btn-danger waves-effect" id="btnRemove">
                            <i class="material-icons">remove_circle</i>
                            REMOVE
                        </a>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
@section scripts{
    <script src="~/Areas/Server/resources/plugins/sweetalert/sweetalert.min.js"></script>
    <script>
        $(function () {
            $('#btnRemove').on('click', function () {
                remove();
            });
        });
        function remove() {
            swal({
                title: "Do you want to remove this voucher?",
                text: "Voucher code: @Model.Code",
                type: "warning",
                showCancelButton: true,
                closeOnConfirm: false,
                showLoaderOnConfirm: true,
            }, function () {
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("Remove")',
                        data: { id: '@Model.Code.Trim()' },
                        success: function () {
                            swal("Remove success!");
                            setTimeout(function () {
                                location.href = "@Url.Action("Index")";
                            }, 500);
                        },
                        complete: function (xhr) {
                            swal(xhr.status);
                        },
                        error: function () {
                            swal("Error when remove, Please try again");
                            setTimeout(function () {
                                location.reload();
                         }, 500);
                     }
                });
            });
        }
    </script>
}

WebNC_Project/Areas/Server/Views/Vouchers/Edit.cshtml
@model WebNC_Project.Models.Voucher

@{
    ViewBag.Title = "Cập nhật Voucher " + Model.Code;
}
@section styles {
    <link href="~/Areas/Server/resources/plugins/bootstrap-datepicker/css/bootstrap-datepicker.css" rel="stylesheet" />
}
<div class="card">
    <div class="header">
        <h2>
            @ViewBag.Title.ToUpper()
        </h2>
    </div>
    <div class="body">
        @using (Html.BeginForm(null, null, FormMethod.Post, new { @id="submitFrm" }))
        {
            @Html.HiddenFor(s => s.Code)
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    @Html.LabelFor(s => s.FromDate)
                    <div class="form-group">
                        <div class="form-line bs_datepicker_from">
                            @Html.EditorFor(s => s.FromDate, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        @Html.ValidationMessageFor(s => s.FromDate, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    @Html.LabelFor(s => s.ToDate)
                    <div class="form-group">
                        <div class="form-line bs_datepicker_to">
                            @Html.EditorFor(s => s.ToDate, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        @Html.ValidationMessageFor(s => s.ToDate, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    @Html.LabelFor(s => s.Condition)
                    <div class="form-group">
                        <div class="form-line">
                            @Html.EditorFor(s => s.Condition, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        @Html.ValidationMessageFor(s => s.Condition, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    @Html.LabelFor(s => s.Discount)
                    <div class="form-group">
                        <div class="form-line">
                            @Html.EditorFor(s => s.Discount, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        @Html.ValidationMessageFor(s => s.Discount, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <button class="btn btn-primary waves-effect" type="submit" onclick="IsSubmit(this, event)">Update</button>
        }
    </div>
</div>
@section scripts {
    <script src="~/Areas/Server/resources/plugins/momentjs/moment.js"></script>
    <script src="~/Areas/Server/resources/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script>
        $(function () {
            $('.bs_datepicker_from input').datepicker({
                autoclose: true,
                container: '.bs_datepicker_from',
                format: 'dd/mm/yyyy' 
            });
            $('.bs_datepicker_to input').datepicker({
                autoclose: true,
                container: '.bs_datepicker_to',
                format: 'dd/mm/yyyy' 
            });
        })
    </script>
}

WebNC_Project/Areas/Server/Views/Vouchers/Index.cshtml
@model IEnumerable<WebNC_Project.Models.Voucher>

@{
    ViewBag.Title = "Danh sách Voucher";
}
@section styles {
    <!--DataTable CSS-->
    <link href="~/Areas/Server/resources/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet" />
}
<div class="card">
    <div class="header">
        <h2>
            @ViewBag.Title.ToUpper()
        </h2>
    </div>
    <div class="body">
        <div class="table-responsive">
            <table id="table" class="table table-bordered table-striped table-hover js-basic-example dataTable">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Code)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FromDate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ToDate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Discount)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Condition)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @item.Code
                            </td>
                            <td>
                                @item.FromDate.ToString("dd/MM/yyyy")
                            </td>
                            <td>
                                @item.ToDate.ToString("dd/MM/yyyy")
                            </td>
                            <td>
                                @item.Discount %
                            </td>
                            <td>
                                &GreaterEqual; @item.Condition
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>


@section scripts{
    <!--DataTable JS-->
    <script src="~/Areas/Server/resources/plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="~/Areas/Server/resources/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script>
        $(function () {
            var table = $('#table').DataTable({
                responsive: true,
                "oSearch": { "sSearch": "@ViewBag.Search" }
            });
            $('#table tbody').on('click', 'tr', function () {
                var data = table.row(this).data();
                var url = '@Url.Action("Details", "Vouchers", new { id = "__id__" })';
                window.location.href = url.replace('__id__',data[0])
            });
        })
    </script>
}