WebNC_Project/Models/Room.cs
namespace WebNC_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            Bookings = new HashSet<Booking>();
            Images = new HashSet<Image>();
            SuppliesForRooms = new HashSet<SuppliesForRoom>();
        }

        [MaxLength(10,ErrorMessage = "{0} contains at most 10 characters")]
        [MinLength(4, ErrorMessage = "{0} contains at least 4 characters")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "{0} is required")]
        [Display(Name = "Mã phòng")]
        public string ID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "{0} is required")]
        [MaxLength(30, ErrorMessage = "{0} contains at most 30 characters")]
        [MinLength(6, ErrorMessage = "{0} contains at least 6 characters")]
        [Display(Name = "Tên phòng")]
        public string Name { get; set; }

        [MaxLength(10, ErrorMessage = "{0} contains at most 10 characters")]
        [MinLength(4, ErrorMessage = "{0} contains at least 4 characters")]
        [Display(Name = "Loại phòng")]
        [Required(ErrorMessage = "{0} is required")]
        public string TypeID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "{0} is required")]
        [Display(Name = "Mô tả")]
        public string Description { get; set; }

        public string Status { get; set; }

        [Display(Name = "Số gười lớn")]
        [Required(ErrorMessage = "{0} is required")]
        [Range(1,10,ErrorMessage = "{0} is in range 1 to 10")]

        public int Adult { get; set; }

        [Display(Name = "Số trẻ em")]
        [Required(ErrorMessage = "{0} is required")]
        [Range(0, 10, ErrorMessage = "{0} is in range 1 to 10")]
        public int Child { get; set; }

        [Display(Name = "Giá thuê")]
        [Required(ErrorMessage = "{0} is required")]
        [Range(1, double.MaxValue, ErrorMessage = "{0} is at min 1")]
        public double Price { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }

        public virtual RoomType RoomType { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuppliesForRoom> SuppliesForRooms { get; set; }

        [NotMapped]
        public string Display
        {
            get
            {
                return $"{ID} : {Name}";
            }
        }
    }
}

WebNC_Project/Models/RoomType.cs
namespace WebNC_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class RoomType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomType()
        {
            Rooms = new HashSet<Room>();
        }

        [Required(ErrorMessage = "{0} is required")]
        [MaxLength(10,ErrorMessage = "{0} contains at most 10 characters")]
        [MinLength(4, ErrorMessage = "{0} contains at least 4 characters")]
        [Display(Name = "Mã loại phòng")]
        public string ID { get; set; }

        [StringLength(30,ErrorMessage = "{0} contains at most 30 characters")]
        [Required(ErrorMessage = "{0} is required")]
        [Display(Name = "Tên loại phòng")]
        public string NameType { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}

WebNC_Project/Areas/Server/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebNC_Project.DAO;
using WebNC_Project.Models;
using System.Web.Mvc;
using System.Threading.Tasks;
using System.IO;

namespace WebNC_Project.Areas.Server.Controllers
{
    [ServerAuthentication]
    public class RoomsController : Controller
    {
        // GET: Server/Rooms
        [ServerAuthorize("WAREHOUSE", "STAFF")]
        public async Task<ActionResult> Index(string search)
        {
            ViewBag.Search = search;
            return View(await RoomDAO.GetAll());
        }

        // GET: Server/Rooms/Details/5
        [ServerAuthorize("WAREHOUSE", "STAFF")]
        public async Task<ActionResult> Details(string id)
        {
            var result = await RoomDAO.GetByID(id);
            return View(result);
        }

        // GET: Server/Rooms/Create/5
        [ServerAuthorize]
        public async Task<ActionResult> Create()
        {
            ViewBag.ListType = await SetListType();
            return View(new Room());
        }

        [HttpPost]
        [ServerAuthorize]
        public async Task<ActionResult> Create(Room model, IEnumerable<HttpPostedFileBase> listimg)
        {
            ViewBag.ListType = await SetListType();
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if(await RoomDAO.GetByID(model.ID) != null)
            {
                ModelState.AddModelError("ID", $"Room ID {model.ID} was existed");
                return View(model);
            }
            try
            {
                await RoomDAO.Create(model);
                if(listimg.ElementAtOrDefault(0) != null)
                {
                    foreach(var img in await Upload(listimg,model.ID))
                    {
                        img.RoomID = model.ID;
                        await ImageDAO.Create(img);
                    }
                }
                return RedirectToAction("Index");
            }
            catch
            {
                ModelState.AddModelError("", "Server can not create room");
                return View(model);
            }
        }

        [ServerAuthorize]
        public async Task<ActionResult> EditInfo(string id)
        {
            ViewBag.ListType = await SetListType();
            return View(await RoomDAO.GetByID(id));
        }

        [HttpPost]
        [ServerAuthorize]
        public async Task<ActionResult> EditInfo(Room model)
        {
            if (await RoomDAO.GetByID(model.ID) == null) return HttpNotFound();
            if(ModelState.IsValid)
            {
                try
                {
                    await RoomDAO.EditInfo(model);
                    return RedirectToAction("Index");
                }
                catch
                {
                    ViewBag.ListType = await SetListType();
                    ModelState.AddModelError("", "Error when update room information");
                    return View(model);
                }
            }
            ViewBag.ListType = await SetListType();
            return View(model);
        }

        [ServerAuthorize]
        public async Task<ActionResult> EditImg(string id)
        {
            ViewBag.IDRoom = id;
            return View(await RoomDAO.GetByID(id));
        }

        [HttpPost]
        [ServerAuthorize]
        public async Task<ActionResult> EditImg(string ID, IEnumerable<HttpPostedFileBase> addnew)
        {
            var room = await RoomDAO.GetByID(ID);
            if (room == null) return HttpNotFound();
            foreach (var img in await Upload(addnew, ID))
            {
                img.RoomID = ID;
                await ImageDAO.Create(img);
            }
            return RedirectToAction("Index");
        }

        [ChildActionOnly]
        public async Task<SelectList> SetListType()
        {
            return new SelectList(await RoomTypeDAO.GetAll(), "ID", "NameType");
        }

        [ChildActionOnly]
        public async Task<IEnumerable<Image>> Upload(IEnumerable<HttpPostedFileBase> listimg, string idroom)
        {
            List<Image> imgs = new List<Image>();
            foreach(var img in listimg)
            {
                FileStream stream;
                string path = Path.Combine(Server.MapPath("~/Content/img/"), img.FileName);
                img.SaveAs(path);
                stream = new FileStream(Path.Combine(path), FileMode.Open);
                imgs.Add(new Image()
                {
                    URL = await ImageDAO.Upload(stream, img.FileName, path, idroom)
                });
            }
            return imgs;
        } 

        [HttpPost]
        [ServerAuthorize]
        public async Task<ActionResult> Remove(string id)
        {
            try
            {
                var enti = await RoomDAO.GetByID(id);
                if (enti == null) return Json("Not found room type with ID: " + id, JsonRequestBehavior.AllowGet);
                await RoomDAO.Remove(id);
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json("Server can not remove this room", JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        [ServerAuthorize]
        public async Task<ActionResult> RemoveImg(string url)
        {
            try
            {
                var img = ImageDAO.GetByURL(url);
                if (img == null) return Json("Not found image", JsonRequestBehavior.AllowGet);
                await ImageDAO.Remove(url);
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json("Server can not remove this image", JsonRequestBehavior.AllowGet);
            }
        }
    }
}

WebNC_Project/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebNC_Project.Models;
using WebNC_Project.DAO;
using System.Threading.Tasks;
using PagedList;
using PagedList.Mvc;

namespace WebNC_Project.Controllers
{
    public class RoomsController : Controller
    {
        // GET: Rooms
        [Obsolete]
        public async Task<ActionResult> Index(int? page, string search, DateTime? datein, DateTime? dateout)
        {
            int pageSize = 6;
            int pageNum = (page ?? 1);
            IEnumerable<Room> result;
            if(search != null || datein.HasValue && dateout.HasValue)
            {
                if(search != null)
                {
                    result = await RoomDAO.Search(search);
                }
                else
                {
                    result = await RoomDAO.GetRoomAvailable(datein.Value, dateout.Value);
                }
            }
            else
            {
                result = await RoomDAO.GetAll();
            }
            return View(result.ToPagedList(pageNum,pageSize));
        }

        public async Task<ActionResult> Details(string id)
        {
            Room room = await RoomDAO.GetByID(id);
            return View(room);
        }
    }
}

WebNC_Project/Areas/Server/Views/Rooms/Create.cshtml
@model WebNC_Project.Models.Room

@{
    ViewBag.Title = "Thêm mới Phòng";
}
@section styles {
    <link href="~/Areas/Server/resources/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />
    <link href="~/Areas/Server/resources/plugins/bootstrap-fileinput/fileinput.css" rel="stylesheet" />
}
<div class="card">
    <div class="header">
        <h2>
            @ViewBag.Title.ToUpper()
        </h2>
    </div>
    <div class="body">
        @using (Html.BeginForm("Create", "Rooms", FormMethod.Post, new { @enctype = "multipart/form-data", @id= "submitFrm" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.LabelFor(s => s.ID)
            <div class="form-group">
                <div class="form-line">
                    @Html.EditorFor(s => s.ID, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                @Html.ValidationMessageFor(s => s.ID, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(s => s.Name)
            <div class="form-group">
                <div class="form-line">
                    @Html.EditorFor(s => s.Name, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                @Html.ValidationMessageFor(s => s.Name, "", new { @class = "text-danger" })
            </div>
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    @Html.LabelFor(s => s.Adult)
                    <div class="form-group">
                        <div class="form-line">
                            @Html.EditorFor(s => s.Adult, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        @Html.ValidationMessageFor(s => s.Adult, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    @Html.LabelFor(s => s.Child)
                    <div class="form-group">
                        <div class="form-line">
                            @Html.EditorFor(s => s.Child, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        @Html.ValidationMessageFor(s => s.Child, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    @Html.LabelFor(s => s.TypeID)
                    <div class="form-group">
                        <div class="form-line">
                            @Html.DropDownListFor(s => s.TypeID, (IEnumerable<SelectListItem>)ViewBag.ListType, new { @class = "selectpicker form-control" })
                        </div>
                        @Html.ValidationMessageFor(s => s.TypeID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    @Html.LabelFor(s => s.Price)
                    <div class="form-group">
                        <div class="form-line">
                            @Html.EditorFor(s => s.Price, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        @Html.ValidationMessageFor(s => s.Price, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            @Html.LabelFor(s => s.Description)
            <div class="form-group">
                <div class="form-line">
                    @Html.EditorFor(s => s.Description, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                @Html.ValidationMessageFor(s => s.Description, "", new { @class = "text-danger" })
            </div>
            <div class="upload-img">
                <label for="listimg">Hình ảnh phòng: </label>
                <div class="form-group">
                    <div class="form-line">
                        <input id="input-file" name="listimg" type="file" class="file" data-preview-file-type="text" multiple>
                    </div>
                </div>
            </div>
            <button class="btn btn-primary waves-effect" type="submit" onclick="IsSubmit(this, event)">SUBMIT</button>
        }
    </div>
</div>
@section scripts {
    <script src="~/Areas/Server/resources/plugins/bootstrap-select/js/bootstrap-select.js"></script>
    <script src="~/Areas/Server/resources/plugins/bootstrap-fileinput/fileinput.js"></script>
    <script>
        $.fn.fileinputBsVersion = "3.3.7";
        $("#input-file").fileinput({
            'showUpload': false,
            browseOnZoneClick: true,
            allowedFileTypes: ['image'],   
            maxFileCount: 5,
        });
        $(function () {
            $('.selectpicker').selectpicker();
            
        })
    </script>
}

WebNC_Project/Areas/Server/Views/Rooms/Details.cshtml
@model WebNC_Project.Models.Room

@{
    ViewBag.Title = "Thông tin phòng ";
    string role = Session["Role"] as string;
}

@section styles {
    <link href="~/Areas/Server/resources/plugins/sweetalert/sweetalert.css" rel="stylesheet" />
}
<div class="card">
    <div class="header">
        <h2>
            @ViewBag.Title.ToUpper()
        </h2>
    </div>
    <div class="body">
        <div class="panel panel-default panel-post">
            <div class="panel-heading">
                <h4>@Html.DisplayNameFor(s => s.ID) : @Model.ID</h4>
            </div>
            <div class="panel-body">
                <div class="list-group font-16">
                    <div class="list-group-item">
                        <div class="row">
                            <div class="col-md-3">
                                @Html.DisplayNameFor(s => s.Name)
                            </div>
                            <div class="col-md-9">
                                @Model.Name
                            </div>
                        </div>
                    </div>
                    <div class="list-group-item">
                        <div class="row">
                            <div class="col-md-3">
                                @Html.DisplayNameFor(s => s.TypeID)
                            </div>
                            <div class="col-md-9">
                                @Model.RoomType.NameType
                            </div>
                        </div>
                    </div>
                    <div class="list-group-item">
                        <div class="row">
                            <div class="col-md-3">
                                @Html.DisplayNameFor(s => s.Adult)
                            </div>
                            <div class="col-md-9">
                                @Model.Adult
                            </div>
                        </div>
                    </div>
                    <div class="list-group-item">
                        <div class="row">
                            <div class="col-md-3">
                                @Html.DisplayNameFor(s => s.Child)
                            </div>
                            <div class="col-md-9">
                                @Model.Child
                            </div>
                        </div>
                    </div>
                    @if (Model.SuppliesForRooms.Count() > 0)
                    {
                        <h5 class="m-l-10">Vật tư sử dụng</h5>
                        <div class="list-group">
                            @foreach (var item in Model.SuppliesForRooms)
                            {
                                <div class="list-group-item">
                                    <div class="row">
                                        <div class="col-md-3">
                                            @item.Supply.Name
                                        </div>
                                        <div class="col-md-3">
                                            @item.Count
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    }
                </div>
                @if (Model.Images.Count() > 0)
                {
                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            @for (int i = 0; i < Model.Images.Count(); i++)
                            {
                                <li data-target="#carousel-example-generic" data-slide-to="@i" class="@(i == 0 ? "active" : "")"></li>
                            }
                        </ol>
                        <div class="carousel-inner" role="listbox">
                            @for (int i = 0; i < Model.Images.Count(); i++)
                            {
                                <div class="item @(i == 0 ? "active" : "") col-md-offset-3 col-md-6 col-sm-12">
                                    <img src="@Model.Images.ElementAt(i).URL" style="width: 100% !important; margin: auto" class="img-responsive center-block" />
                                </div>
                            }
                        </div>
                        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                }
            </div>
            @if (role == "MANAGER")
            {
                <div class="panel-footer">
                    <div class="btn-group btn-group-justified" role="group" aria-label="Justified button group">
                        <a href="@Url.Action("EditInfo","Rooms", new { id = Model.ID.Trim() })" class="btn btn-primary waves-effect">
                            <i class="material-icons">edit</i>
                            <span>EDIT INFO</span>
                        </a>
                        <a href="@Url.Action("EditImg","Rooms", new { id = Model.ID.Trim() })" class="btn btn-toolbar waves-effect">
                            <i class="material-icons">image</i>
                            <span>EDIT IMAGE</span>
                        </a>
                        <a href="javascript:void(0);" role="button" class="btn btn-danger waves-effect" id="btnRemove">
                            <i class="material-icons">remove_circle</i>
                            <span>REMOVE</span>
                        </a>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
@section scripts{
    <script src="~/Areas/Server/resources/plugins/sweetalert/sweetalert.min.js"></script>
    <script>
        $(function () {
            $('#btnRemove').on('click', function () {
                remove();
            });
        });
        function remove() {
            swal({
                title: "Do you want to remove this room?",
                text: "Room id: @Model.ID",
                type: "warning",
                showCancelButton: true,
                closeOnConfirm: false,
                showLoaderOnConfirm: true,
            }, function () {
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("Remove")',
                        data: { id: '@Model.ID.Trim()' },
                        success: function (res) {
                            if (res === true) {
                                swal("Remove success!");
                                setTimeout(function () {
                                    location.href = "@Url.Action("Index")";
                                }, 500);
                            }
                            else swal(res);
                        },
                        complete: function (xhr) {
                            swal(xhr.status);
                        },
                        error: function () {
                            swal("Error when remove, Please try again");
                            setTimeout(function () {
                                location.reload();
                         }, 500);
                     }
                });
            });
        }
    </script>
}

WebNC_Project/Areas/Server/Views/Rooms/EditImg.cshtml
@model WebNC_Project.Models.Room

@{
    ViewBag.Title = "Quản lý ảnh phòng " + Model.ID;
}
@section styles {
    <link href="~/Areas/Server/resources/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />
    <link href="~/Areas/Server/resources/plugins/bootstrap-fileinput/fileinput.css" rel="stylesheet" />
    <link href="~/Areas/Server/resources/plugins/light-gallery/css/lightgallery.css" rel="stylesheet" />
    <link href="~/Areas/Server/resources/plugins/sweetalert/sweetalert.css" rel="stylesheet" />
}
<div class="card">
    <div class="header">
        <h2>
            @ViewBag.Title.ToUpper()
        </h2>
    </div>
    <div class="body">
        <div id="aniimated-thumbnials" class="row clearfix list-unstyled justified-gallery">
            @foreach (var img in Model.Images)
            {
                <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                    <a href="@img.URL">
                        <img src="@img.URL" class="img-responsive" />
                    </a>
                </div>
            }
        </div>
        @using (Html.BeginForm("EditImg", "Rooms", FormMethod.Post, new { @enctype = "multipart/form-data", @id="submitFrm" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(s => s.ID)
            <div class="upload-img">
                <label for="addnew">Thêm ảnh mới: </label>
                <div class="form-group">
                    <div class="form-line">
                        <input id="input-file" name="addnew" type="file" class="file" data-preview-file-type="text" multiple>
                    </div>
                </div>
            </div>
            <button class="btn btn-primary waves-effect" type="submit" onclick="IsSubmit(this, event)">SUBMIT</button>
        }
    </div>
</div>
@section scripts {
    <script src="~/Areas/Server/resources/plugins/bootstrap-select/js/bootstrap-select.js"></script>
    <script src="~/Areas/Server/resources/plugins/bootstrap-fileinput/fileinput.js"></script>
    <script src="~/Areas/Server/resources/plugins/light-gallery/js/lightgallery-all.js"></script>
    <script src="~/Areas/Server/resources/plugins/sweetalert/sweetalert.min.js"></script>
    <script>
        $.fn.fileinputBsVersion = "3.3.7";
        $("#input-file").fileinput({
            'showUpload': false,
            browseOnZoneClick: true,
            allowedFileTypes: ['image'],
            maxFileCount: 5,
        });
        $('#aniimated-thumbnials').lightGallery({
            thumbnail: true,
            selector: 'a',
        });
        $(document).on('click', ".lg-object.lg-image", function (event) {
            var urlImg = event.target.src;
            swal({
                title: "Do you want to remove this image?",
                type: "warning",
                showCancelButton: true,
                closeOnConfirm: false,
                showLoaderOnConfirm: true,
            },function () {
                    $.post("@Url.Action("RemoveImg")", { url: urlImg }, function (res) {
                        if (res === true) {
                            swal("Remove success!");
                            setTimeout(function () {
                                location.href = "@Url.Action("EditImg")"
                            }, 1000);
                        }
                        else swal(res)
                    })
            })
        })
        $('.selectpicker').selectpicker();
    </script>
}

WebNC_Project/Areas/Server/Views/Rooms/Index.cshtml
@model IEnumerable<WebNC_Project.Models.Room>

@{
    ViewBag.Title = "Danh sách phòng";
}
@section styles {
    <!--DataTable CSS-->
    <link href="~/Areas/Server/resources/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet" />
}
<div class="card">
    <div class="header">
        <h2>
            @ViewBag.Title.ToUpper()
        </h2>
    </div>
    <div class="body">
        <div class="table-responsive">
            <table id="table" class="table table-bordered table-striped table-hover js-basic-example dataTable">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.ID)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.TypeID)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Adult)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Child)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Price)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Images)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @item.ID
                            </td>
                            <td>
                                @item.Name
                            </td>
                            <td>
                                @item.RoomType.NameType
                            </td>
                            <td>
                                @item.Adult
                            </td>
                            <td>
                                @item.Child
                            </td>
                            <td>
                                @item.Price $
                            </td>
                            <td>
                                @item.Images.Count()
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>


@section scripts{
    <!--DataTable JS-->
    <script src="~/Areas/Server/resources/plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="~/Areas/Server/resources/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script>
        $(function () {
            var table = $('#table').DataTable({
                responsive: true,
                "oSearch": { "sSearch": "@ViewBag.Search" }
            });
            $('#table tbody').on('click', 'tr', function () {
                var data = table.row(this).data();
                var url = '@Url.Action("Details", "Rooms", new { id = "__id__" })';
                window.location.href = url.replace('__id__',data[0])
            });
        })
    </script>
}