WebNC_Project/Models/Service.cs
namespace WebNC_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            BookingServices = new HashSet<BookingServices>();
        }

        [StringLength(10, ErrorMessage = "{0} is contains at most 10 characters")]
        [Required(ErrorMessage = "{0} is required")]
        [Display(Name = "Mã dịch vụ")]
        public string ID { get; set; }

        [Required(ErrorMessage = "{0} is required")]
        [Display(Name = "Tên dịch vụ")]
        public string Name { get; set; }

        [Required(ErrorMessage = "{0} is required")]
        [Display(Name = "Mô tả")]
        public string Description { get; set; }

        [Required(ErrorMessage = "{0} is required")]
        [Range(1, double.MaxValue, ErrorMessage = "Please enter valid price")]
        [Display(Name = "Giá dịch vụ")]
        public double Price { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingServices> BookingServices { get; set; }

        [NotMapped]
        public string Display
        {
            get
            {
                return $"{Name} (Price:{Price} $)";
            }
        }
    }
}

WebNC_Project/Areas/Server/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebNC_Project.DAO;
using WebNC_Project.Models;
using System.Threading.Tasks;

namespace WebNC_Project.Areas.Server.Controllers
{
    [ServerAuthentication]
    public class ServicesController : Controller
    {
        // GET: Server/Services
        [ServerAuthorize("STAFF")]
        public async Task<ActionResult> Index(string search)
        {
            ViewBag.Search = search;
            return View(await ServiceDAO.GetAll());
        }

        // GET: Server/Services/Details/5
        [ServerAuthorize("STAFF")]
        public async Task<ActionResult> Details(string id)
        {
            Service result = await ServiceDAO.GetByID(id);
            return View(result);
        }

        // GET: Server/Services/Create
        [ServerAuthorize]
        public ActionResult Create()
        {
            return View(new Service());
        }

        // POST: Server/Services/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        [ServerAuthorize]
        public async Task<ActionResult> Create(Service service)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var entity = await ServiceDAO.GetByID(service.ID);
                    if (entity != null)
                    {
                        ModelState.AddModelError(service.ID, $"The services {service.ID} existed");
                        return View(service);
                    }
                    await ServiceDAO.Create(service);
                    return RedirectToAction("Index");
                }
                return View(service);
            }
            catch
            {
                ModelState.AddModelError("", "Server can not create services");
                return View(service);
            }
        }

        // GET: Server/Services/Edit/5
        [ServerAuthorize]
        public async Task<ActionResult> Edit(string id)
        {
            Service service = await ServiceDAO.GetByID(id);
            return View(service);
        }

        // POST: Server/Services/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        [ServerAuthorize]
        public async Task<ActionResult> Edit(Service service)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await ServiceDAO.Edit(service);
                    return RedirectToAction("Details", new { id = service.ID.Trim() });
                }
                return View(service);

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(service);
            }
        }

        // POST: Server/Services/Delete/5
        [HttpPost]
        [ServerAuthorize]
        public async Task<ActionResult> Remove(string id)
        {
            var result = await ServiceDAO.GetByID(id);
            if (result == null) return new HttpStatusCodeResult(System.Net.HttpStatusCode.NotFound);
            try
            {
                await ServiceDAO.Remove(id);
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.OK);
            }
            catch
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
        }
    }
}

WebNC_Project/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebNC_Project.DAO;
using WebNC_Project.Models;
using PagedList;
using PagedList.Mvc;

namespace WebNC_Project.Controllers
{
    public class ServiceController : Controller
    {
        // GET: Service
        public async Task<ActionResult> Index(int? page, string search)
        {
            int pageSize = 6;
            int pageNum = (page ?? 1);
            IEnumerable<Service> result;
            if(search == null)
            {
                result = await ServiceDAO.GetAll();
            }
            else
            {
                result = await ServiceDAO.Search(search);
            }
            return View(result.ToPagedList(pageNum,pageSize));
        }

        public async Task<ActionResult> Details(string id)
        {
            var result = await ServiceDAO.GetByID(id);
            return View(result);
        }
    }
}

WebNC_Project/Areas/Server/Views/Services/Create.cshtml
@model WebNC_Project.Models.Service

@{
    ViewBag.Title = "Thêm mới dịch vụ";
}
<div class="card">
    <div class="header">
        <h2>
            @ViewBag.Title.ToUpper()
        </h2>
    </div>
    <div class="body">
        @using (Html.BeginForm("Create", "Services", FormMethod.Post, new { @id = "submitFrm" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @Html.LabelFor(s => s.ID)
            <div class="form-group">
                <div class="form-line">
                    @Html.EditorFor(s => s.ID, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                @Html.ValidationMessageFor(s => s.ID, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(s => s.Name)
            <div class="form-group">
                <div class="form-line">
                    @Html.EditorFor(s => s.Name, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                @Html.ValidationMessageFor(s => s.Name, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(s => s.Price)
            <div class="form-group">
                <div class="form-line">
                    @Html.EditorFor(s => s.Price, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                @Html.ValidationMessageFor(s => s.Price, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(s => s.Description)
            <div class="form-group">
                <div class="form-line">
                    @Html.TextAreaFor(s => s.Description)
                </div>
                @Html.ValidationMessageFor(s => s.Description, "", new { @class = "text-danger" })
            </div>
            <button class="btn btn-primary waves-effect" type="submit" onclick="IsSubmit(this, event)">SUBMIT</button>
        }
    </div>
</div>
@section scripts{
    <script src="~/Areas/Server/resources/plugins/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('Description');
    </script>
}

WebNC_Project/Areas/Server/Views/Services/Details.cshtml
@model WebNC_Project.Models.Service

@{
    ViewBag.Title = "Chi tiết dịch vụ";
    string role = Session["Role"] as string;
}
@section styles {
    <link href="~/Areas/Server/resources/plugins/sweetalert/sweetalert.css" rel="stylesheet" />
}
<div class="card">
    <div class="header">
        <h2>
            @ViewBag.Title.ToUpper()
        </h2>
    </div>
    <div class="body">
        <div class="panel panel-default panel-post">
            <div class="panel-heading">
                <h4>Mã dịch vụ : @Model.ID</h4>
            </div>
            <div class="panel-body">
                <div class="list-group font-16">
                    <div class="list-group-item">
                        <div class="row">
                            <div class="col-md-3">
                                @Html.DisplayNameFor(s => s.Name)
                            </div>
                            <div class="col-md-9">
                                @Html.DisplayFor(s => s.Name)
                            </div>
                        </div>
                    </div>
                    <div class="list-group-item">
                        <div class="row">
                            <div class="col-md-3">
                                @Html.DisplayNameFor(s => s.Price)
                            </div>
                            <div class="col-md-9">
                                @Html.DisplayFor(s => s.Price) $
                            </div>
                        </div>
                    </div>
                    <div class="list-group-item">
                        <div class="row">
                            <div class="col-md-3">
                                @Html.DisplayNameFor(s => s.Description)
                            </div>
                            <div class="col-md-9">
                                @Html.Raw(Model.Description)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @if (role == "MANAGER")
            {
                <div class="panel-footer">
                    <div class="btn-group btn-group-justified" role="group" aria-label="Justified button group">
                        <a href="@Url.Action("Edit","Services", new { id = Model.ID.Trim() })" class="btn btn-primary waves-effect">
                            <i class="material-icons">edit</i>
                            <span>EDIT</span>
                        </a>
                        <a href="javascript:void(0);" onclick="Remove()" role="button" class="btn btn-danger waves-effect" id="btnRemove">
                            <i class="material-icons">remove_circle</i>
                            REMOVE
                        </a>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
@section scripts{
    <script src="~/Areas/Server/resources/plugins/sweetalert/sweetalert.min.js"></script>
    <script>
        $(function () {
            $('#btnRemove').on('click', function () {
                remove();
            });
        });
        function Remove() {
            swal({
                title: "Do you want to remove this services?",
                text: "Services ID: @Model.ID",
                type: "warning",
                showCancelButton: true,
                closeOnConfirm: false,
                showLoaderOnConfirm: true,
            }, function () {
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("Remove","Services")',
                        data: { id: '@Model.ID.Trim()' },
                        success: function () {
                            swal("Remove success!");
                            setTimeout(function () {
                                location.href = "@Url.Action("Index")";
                            }, 500);
                        },
                        complete: function (xhr) {
                            swal(xhr.status);
                        },
                        error: function () {
                            swal("Error when remove, Please try again");
                            setTimeout(function () {
                                location.reload();
                         }, 500);
                     }
                });
            });
        }
    </script>
}

WebNC_Project/Areas/Server/Views/Services/Edit.cshtml
@model WebNC_Project.Models.Service

@{
    ViewBag.Title = "Cập nhật dịch vụ " + Model.ID;
}
<div class="card">
    <div class="header">
        <h2>
            @ViewBag.Title.ToUpper()
        </h2>
    </div>
    <div class="body">
        @using (Html.BeginForm("Edit", "Services", FormMethod.Post, new { @id = "submitFrm" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @Html.LabelFor(s => s.Name)
            <div class="form-group">
                <div class="form-line">
                    @Html.EditorFor(s => s.Name, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                @Html.ValidationMessageFor(s => s.Name, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(s => s.Price)
            <div class="form-group">
                <div class="form-line">
                    @Html.EditorFor(s => s.Price, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                @Html.ValidationMessageFor(s => s.Price, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(s => s.Description)
            <div class="form-group">
                <div class="form-line">
                    @Html.TextAreaFor(s => s.Description, new { @class = "form-control no-resize auto-growth" })
                </div>
                @Html.ValidationMessageFor(s => s.Description, "", new { @class = "text-danger" })
            </div>
            <button class="btn btn-primary waves-effect" type="submit" onclick="IsSubmit(this, event)">Update</button>
        }
    </div>
</div>

@section scripts{
    <script src="~/Areas/Server/resources/plugins/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('Description');
    </script>
}

WebNC_Project/Areas/Server/Views/Services/Index.cshtml
@model IEnumerable<WebNC_Project.Models.Service>

@{
    ViewBag.Title = "Danh sách dịch vụ";
}
@section styles {
    <!--DataTable CSS-->
    <link href="~/Areas/Server/resources/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet" />
}
<div class="card">
    <div class="header">
        <h2>
            @ViewBag.Title.ToUpper()
        </h2>
    </div>
    <div class="body">
        <div class="table-responsive">
            <table id="table" class="table table-bordered table-striped table-hover js-basic-example dataTable">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.ID)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Price)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @item.ID
                            </td>
                            <td>
                                @item.Name
                            </td>
                            <td>
                                @item.Price $
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>


@section scripts{
    <!--DataTable JS-->
    <script src="~/Areas/Server/resources/plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="~/Areas/Server/resources/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script>
        $(function () {
            var table = $('#table').DataTable({
                responsive: true,
                "oSearch": { "sSearch": "@ViewBag.Search" }
            });
            $('#table tbody').on('click', 'tr', function () {
                var data = table.row(this).data();
                var url = '@Url.Action("Details", "Services", new { id = "__id__" })';
                window.location.href = url.replace('__id__',data[0])
            });
        })
    </script>
}